### ISSUE TITLE
ACON: Enable happy path test

### ISSUE THREAD

**Issue by ffallahadl** [intel/ACON#19]
### Tasks

- [x] Build acond using `scripts/acon-build.env` script in happy path.
- [x] Add image spec test in happy path.
- [x] Add get quote test cases

**Comment by billionairiam** [comment]
-[x] Build acond using cedric's script
-[x] Add image spec test

**Comment by binxing** [comment]
@binxing will compare JSON manifest against spec to make sure all defined fields are covered in happy path test.
